variable "tenancy_ocid" {
  description = "OCI tenancy OCID (the root compartment)."
  type        = string
}

variable "region" {
  description = "OCI region used by the lab."
  type        = string
  default     = "us-chicago-1"
}

variable "home_region" {
  description = "OCI tenancy home region used for IAM and Identity Domains control-plane resources."
  type        = string
  validation {
    condition     = can(regex("^[a-z]{2}-[a-z0-9-]+-[0-9]+$", var.home_region))
    error_message = "home_region must be an OCI region identifier such as us-ashburn-1."
  }
}

variable "operator_user_ocid" {
  description = "OCI user OCID from the Deploy Studio config persisted on the registration VM."
  type        = string
  validation {
    condition     = can(regex("^ocid1\\.user\\.", var.operator_user_ocid))
    error_message = "operator_user_ocid must be an OCI user OCID."
  }
}

variable "compartment_ocid" {
  description = "Target compartment already created or resolved by Deploy Studio."
  type        = string
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by Deploy Studio."
  type        = string
}

variable "deployment_suffix" {
  description = "Optional stable lowercase suffix supplied by Deploy Studio."
  type        = string
  default     = ""
  validation {
    condition     = var.deployment_suffix == "" || can(regex("^[a-z0-9]{4,12}$", var.deployment_suffix))
    error_message = "deployment_suffix must contain 4-12 lowercase letters or digits."
  }
}

variable "admin_username" {
  description = "Local lab administrator username."
  type        = string
  default     = "admin"
  validation {
    condition     = can(regex("^[A-Za-z0-9._-]{3,64}$", var.admin_username))
    error_message = "admin_username must be 3-64 safe username characters."
  }
}

variable "admin_password_hash" {
  description = "PBKDF2 hash generated by Deploy Studio; plaintext is never accepted."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.admin_password_hash, "pbkdf2_sha256$")
    error_message = "admin_password_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "registration_code_hash" {
  description = "PBKDF2 hash of the normalized registration code."
  type        = string
  sensitive   = true
  validation {
    condition     = startswith(var.registration_code_hash, "pbkdf2_sha256$")
    error_message = "registration_code_hash must use the Deploy Studio PBKDF2 format."
  }
}

variable "agent_model_id" {
  description = "ACTIVE on-demand OCI Generative AI CHAT model selected in Deploy Studio for participant governance agents."
  type        = string
  validation {
    condition     = length(trimspace(var.agent_model_id)) > 0
    error_message = "agent_model_id must identify the selected regional CHAT model."
  }
}

variable "autonomous_database_mode" {
  description = "Whether this deployment creates or reuses its Autonomous AI Database."
  type        = string
  default     = "new"
  validation {
    condition     = contains(["new", "existing"], var.autonomous_database_mode)
    error_message = "autonomous_database_mode must be new or existing."
  }
}

variable "autonomous_database_version" {
  description = "Autonomous AI Database version."
  type        = string
  default     = "26ai"
}

variable "autonomous_database_workload" {
  description = "Autonomous AI Database workload."
  type        = string
  default     = "DW"
}

variable "autonomous_database_compute_count" {
  description = "ECPU count for a new Autonomous AI Database; Deploy Studio starts at four."
  type        = number
  default     = 4
}

variable "existing_autonomous_database_ocid" {
  description = "OCID of the existing Autonomous AI Database when database mode is existing."
  type        = string
  default     = ""
}

variable "autonomous_database_admin_password" {
  description = "ADMIN password supplied to Autonomous and the idempotent post-apply hook."
  type        = string
  sensitive   = true
  validation {
    condition     = length(var.autonomous_database_admin_password) >= 12
    error_message = "autonomous_database_admin_password must contain at least 12 characters."
  }
}

variable "autonomous_database_wallet_password" {
  description = "Password used to create or open the Autonomous wallet."
  type        = string
  sensitive   = true
  validation {
    condition     = length(var.autonomous_database_wallet_password) >= 12
    error_message = "autonomous_database_wallet_password must contain at least 12 characters."
  }
}

variable "enable_ai_data_governance" {
  description = "Install the optional AI Data Governance Gateway in a private OKE cluster."
  type        = bool
  default     = false
}

variable "governance_gateway_image" {
  description = "Immutable gateway image resolved by the authenticated deployment preflight."
  type        = string
  default     = ""
}

variable "governance_gateway_oidc_issuer" {
  description = "HTTPS issuer discovered from the active default OCI Identity Domain."
  type        = string
  default     = ""
}

variable "governance_gateway_oidc_authority" {
  description = "Active default OCI Identity Domain URL discovered by the deployment preflight."
  type        = string
  default     = ""
}

variable "governance_gateway_oidc_static_jwks_json" {
  description = "Current public RSA signing keys retrieved through authenticated Identity Domains preflight."
  type        = string
  default     = ""
}

variable "preferred_vm_shape" {
  description = "Server-selected E5/E4/E3 Flex shape from the trusted capacity preflight."
  type        = string
  default     = "VM.Standard.E5.Flex"
  validation {
    condition     = contains(["VM.Standard.E5.Flex", "VM.Standard.E4.Flex", "VM.Standard.E3.Flex"], var.preferred_vm_shape)
    error_message = "preferred_vm_shape must be E5 Flex, E4 Flex, or E3 Flex."
  }
}

variable "_oci_instance" {
  description = "Compute defaults aligned with the Select AI Analyzer application host."

  default = {
    shape = {
      name          = "VM.Standard.E5.Flex"
      ocpus         = 2
      memory_in_gbs = 16
    }
  }
}

variable "availability_domain_index" {
  description = "Zero-based availability domain index."
  type        = number
  default     = 0
}

variable "_oci_vcn" {
  description = "VCN defaults aligned with the Select AI Analyzer application host."

  default = {
    cidr_block        = "10.10.0.0/24"
    ingress_tcp_ports = [80, 443]
  }
}

variable "_oci_governance" {
  description = "Private OKE network and worker defaults for the optional governance gateway."

  default = {
    vcn_cidr             = "10.11.0.0/16"
    endpoint_subnet_cidr = "10.11.0.0/28"
    worker_subnet_cidr   = "10.11.1.0/24"
    service_subnet_cidr  = "10.11.2.0/24"
    gateway_subnet_cidr  = "10.11.3.0/28"
    gateway_backend_ip   = "10.11.2.10"
    node_shape           = "VM.Standard.E4.Flex"
    node_ocpus           = 2
    node_memory_in_gbs   = 16
    node_count           = 2
  }
}

variable "source_repository_url" {
  description = "Trusted public source repository cloned by the VM."
  type        = string
  default     = "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
  validation {
    condition     = var.source_repository_url == "https://github.com/jgangini/oci-aidp-cloud-migration-lab.git"
    error_message = "Only the trusted AIDP lab repository is accepted."
  }
}

variable "source_commit_sha" {
  description = "Immutable full source SHA supplied by Deploy Studio."
  type        = string
  validation {
    condition     = can(regex("^[0-9a-f]{40}$", var.source_commit_sha))
    error_message = "source_commit_sha must be a full lowercase Git SHA."
  }
}
