"""Operational store facade; Autonomous procedures remain for legacy migration only."""
from __future__ import annotations

import json
import re

from .core import canonical_mode
from . import control_store
from .post_index import published_time
from .control_store import DOCUMENT_NAME, ObjectControlStore, _valid_name

TABLES = (
    "CREATE TABLE ADMIN.PRISMA_CONTROL_DOCS (name VARCHAR2(100) PRIMARY KEY, payload CLOB NOT NULL CHECK (payload IS JSON))",
    "CREATE TABLE ADMIN.PRISMA_PUBLICATIONS (version VARCHAR2(100) PRIMARY KEY, payload CLOB NOT NULL CHECK (payload IS JSON), published_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP)",
    """CREATE TABLE ADMIN.PRISMA_SOCIAL_POSTS (
       capture_seq NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY UNIQUE,
       post_key VARCHAR2(200) PRIMARY KEY, platform VARCHAR2(50) NOT NULL,
       published_at VARCHAR2(50) NOT NULL, analysis_status VARCHAR2(20) NOT NULL,
       payload CLOB NOT NULL CHECK (payload IS JSON),
       CONSTRAINT PRISMA_POST_STATUS CHECK (analysis_status IN ('captured','ingested','processed')))""",
    "CREATE INDEX ADMIN.PRISMA_POST_PLATFORM_SEQ ON ADMIN.PRISMA_SOCIAL_POSTS(platform,capture_seq)",
    "ALTER TABLE ADMIN.PRISMA_SOCIAL_POSTS ADD captured_at VARCHAR2(50)",
    "ALTER TABLE ADMIN.PRISMA_SOCIAL_POSTS ADD listing_published_at VARCHAR2(40)",
    "ALTER TABLE ADMIN.PRISMA_SOCIAL_POSTS ADD listing_revision NUMBER DEFAULT 0 NOT NULL",
    "CREATE SEQUENCE ADMIN.PRISMA_POST_LIST_REVISION ORDER",
    "CREATE INDEX ADMIN.PRISMA_POST_PUBLICATION_SEQ ON ADMIN.PRISMA_SOCIAL_POSTS(platform,listing_published_at,capture_seq)",
)

PACKAGE_SPEC = """CREATE OR REPLACE PACKAGE ADMIN.PRISMA_CONTROL AUTHID DEFINER AS
  FUNCTION READ_DOC(p_name VARCHAR2) RETURN CLOB;
  FUNCTION READ_DOCS(p_names CLOB) RETURN CLOB;
  PROCEDURE WRITE_DOC(p_name VARCHAR2, p_document CLOB, p_expected NUMBER);
  PROCEDURE PUBLISH(p_version VARCHAR2, p_document CLOB);
  PROCEDURE UPSERT_POSTS(p_document CLOB, p_status VARCHAR2);
  FUNCTION LIST_POSTS(p_platform VARCHAR2, p_limit NUMBER, p_before NUMBER, p_max NUMBER) RETURN CLOB;
  FUNCTION LIST_ORDERED_POSTS(p_platform VARCHAR2, p_limit NUMBER, p_before VARCHAR2, p_id VARCHAR2,
    p_max NUMBER, p_sort VARCHAR2, p_order VARCHAR2) RETURN CLOB;
  FUNCTION RESET_VERSION RETURN NUMBER;
  FUNCTION SENSOR_RESET_VERSION RETURN NUMBER;
  FUNCTION PURGE_SYNTHETIC_POSTS(p_operation_id VARCHAR2) RETURN NUMBER;
  FUNCTION LIST_PUBLICATIONS(p_after VARCHAR2) RETURN CLOB;
  PROCEDURE REPLACE_SYNTHETIC_PUBLICATION(p_operation_id VARCHAR2, p_old VARCHAR2, p_new VARCHAR2);
  PROCEDURE REPLACE_SENSOR_PUBLICATION(p_operation_id VARCHAR2, p_sensor_type VARCHAR2, p_old VARCHAR2, p_new VARCHAR2);
END PRISMA_CONTROL;"""

PACKAGE_BODY = """CREATE OR REPLACE PACKAGE BODY ADMIN.PRISMA_CONTROL AS
  FUNCTION RESET_VERSION RETURN NUMBER IS BEGIN RETURN 3; END;
  FUNCTION SENSOR_RESET_VERSION RETURN NUMBER IS BEGIN RETURN 3; END;
  FUNCTION gold_replacement(p_old VARCHAR2, p_new VARCHAR2) RETURN BOOLEAN
  IS v_payload CLOB; v_document JSON_OBJECT_T; v_replacements JSON_OBJECT_T;
  BEGIN
    IF p_old IS NULL OR p_new IS NULL OR p_old=p_new THEN RETURN FALSE; END IF;
    SELECT checkpoint.payload INTO v_payload FROM ADMIN.PRISMA_CONTROL_DOCS checkpoint
      WHERE checkpoint.name='checkpoint_reset' AND EXISTS (
        SELECT 1 FROM ADMIN.PRISMA_CONTROL_DOCS runtime WHERE runtime.name='runtime'
          AND JSON_VALUE(runtime.payload,'$.analytics_store')='gold');
    v_document:=JSON_OBJECT_T.parse(v_payload);
    v_replacements:=v_document.get_object('replacements');
    IF v_replacements IS NULL OR NOT v_replacements.has(p_old) THEN RETURN FALSE; END IF;
    -- The active reset journals this pair only after Gold and its object publication are durable.
    IF v_replacements.get_string(p_old)=p_new THEN RETURN TRUE; END IF;
    RETURN FALSE;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN FALSE;
  END;
  PROCEDURE require_reset(p_operation_id VARCHAR2) IS v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM ADMIN.PRISMA_CONTROL_DOCS WHERE name='checkpoint_reset'
      AND JSON_VALUE(payload,'$.operation_id')=p_operation_id
      AND JSON_VALUE(payload,'$.sensor_type') IS NULL
      AND JSON_VALUE(payload,'$.status')='pending'
      AND JSON_VALUE(payload,'$.ready')='true';
    IF v_count!=1 THEN RAISE_APPLICATION_ERROR(-20002,'Synthetic reset is not active'); END IF;
  END;
  FUNCTION PURGE_SYNTHETIC_POSTS(p_operation_id VARCHAR2) RETURN NUMBER IS v_count NUMBER;
  BEGIN
    require_reset(p_operation_id);
    DELETE FROM ADMIN.PRISMA_SOCIAL_POSTS WHERE JSON_VALUE(payload,'$.mode') IN ('Synthetic','simulation');
    v_count:=SQL%ROWCOUNT;
    RETURN v_count;
  END;
  FUNCTION LIST_PUBLICATIONS(p_after VARCHAR2) RETURN CLOB IS v_result CLOB;
  BEGIN
    SELECT COALESCE(JSON_ARRAYAGG(payload FORMAT JSON RETURNING CLOB),TO_CLOB('[]')) INTO v_result
    FROM (SELECT payload FROM ADMIN.PRISMA_PUBLICATIONS WHERE p_after IS NULL OR version>p_after
      ORDER BY version FETCH FIRST 1 ROWS ONLY);
    RETURN v_result;
  END;
  PROCEDURE REPLACE_SYNTHETIC_PUBLICATION(p_operation_id VARCHAR2, p_old VARCHAR2, p_new VARCHAR2)
  IS v_count NUMBER;
  BEGIN
    require_reset(p_operation_id);
    SELECT COUNT(*) INTO v_count FROM ADMIN.PRISMA_PUBLICATIONS WHERE version=p_new AND version!=p_old
      AND NOT JSON_EXISTS(payload,'$.evidence[*]?(@.mode == "Synthetic" || @.mode == "simulation")')
      AND NOT JSON_EXISTS(payload,'$.incidents[*]?(@.mode == "Synthetic" || @.mode == "simulation")');
    IF v_count!=1 AND NOT gold_replacement(p_old,p_new)
    THEN RAISE_APPLICATION_ERROR(-20002,'Clean replacement publication is missing'); END IF;
    DELETE FROM ADMIN.PRISMA_PUBLICATIONS WHERE version=p_old AND (
      JSON_EXISTS(payload,'$.evidence[*]?(@.mode == "Synthetic" || @.mode == "simulation")') OR
      JSON_EXISTS(payload,'$.incidents[*]?(@.mode == "Synthetic" || @.mode == "simulation")'));
  END;
  PROCEDURE REPLACE_SENSOR_PUBLICATION(p_operation_id VARCHAR2, p_sensor_type VARCHAR2, p_old VARCHAR2, p_new VARCHAR2)
  IS v_count NUMBER;
  BEGIN
    IF p_sensor_type IS NULL OR p_sensor_type NOT IN ('all','river_level','rainfall','temperature','soil_moisture','wind_speed')
    THEN RAISE_APPLICATION_ERROR(-20002,'Invalid sensor reset type'); END IF;
    SELECT COUNT(*) INTO v_count FROM ADMIN.PRISMA_CONTROL_DOCS WHERE name='checkpoint_reset'
      AND JSON_VALUE(payload,'$.operation_id')=p_operation_id
      AND JSON_VALUE(payload,'$.sensor_type')=p_sensor_type
      AND JSON_VALUE(payload,'$.status')='pending'
      AND JSON_VALUE(payload,'$.ready')='true';
    IF v_count!=1 THEN RAISE_APPLICATION_ERROR(-20002,'Sensor reset is not active'); END IF;
    SELECT COUNT(*) INTO v_count FROM ADMIN.PRISMA_PUBLICATIONS WHERE version=p_new AND version!=p_old
      AND NOT JSON_EXISTS(payload,'$.sensors[*]?(($kind == "all" || @.sensor_type == $kind) && (@.sensor_type == "river_level" || @.sensor_type == "rainfall" || @.sensor_type == "temperature" || @.sensor_type == "soil_moisture" || @.sensor_type == "wind_speed") && (@.mode == "Synthetic" || @.mode == "simulation") && @.is_simulated == true)'
        PASSING p_sensor_type AS "kind" ERROR ON ERROR);
    IF v_count!=1 AND NOT gold_replacement(p_old,p_new)
    THEN RAISE_APPLICATION_ERROR(-20002,'Clean sensor replacement publication is missing'); END IF;
    DELETE FROM ADMIN.PRISMA_PUBLICATIONS WHERE version=p_old
      AND JSON_EXISTS(payload,'$.sensors[*]?(($kind == "all" || @.sensor_type == $kind) && (@.sensor_type == "river_level" || @.sensor_type == "rainfall" || @.sensor_type == "temperature" || @.sensor_type == "soil_moisture" || @.sensor_type == "wind_speed") && (@.mode == "Synthetic" || @.mode == "simulation") && @.is_simulated == true)'
        PASSING p_sensor_type AS "kind" ERROR ON ERROR);
  END;
  PROCEDURE valid_name(p_name VARCHAR2) IS BEGIN
    IF p_name IS NULL OR LENGTH(p_name) > 100 OR NOT REGEXP_LIKE(p_name, '^(configuration|simulation|reviews|runtime|event_registry|status_[a-z]+|checkpoint_[a-z]+)$')
    THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid Gods Eye View document'); END IF;
  END;
  FUNCTION READ_DOC(p_name VARCHAR2) RETURN CLOB IS v_doc CLOB;
  BEGIN
    valid_name(p_name);
    SELECT payload INTO v_doc FROM ADMIN.PRISMA_CONTROL_DOCS WHERE name = p_name;
    RETURN v_doc;
  EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
  END;
  FUNCTION READ_DOCS(p_names CLOB) RETURN CLOB IS v_result CLOB; v_count NUMBER; v_unique NUMBER;
  BEGIN
    IF p_names IS NULL OR SUBSTR(TRIM(p_names),1,1)!='['
    THEN RAISE_APPLICATION_ERROR(-20002,'Invalid Gods Eye View documents'); END IF;
    SELECT COUNT(*),COUNT(DISTINCT name) INTO v_count,v_unique
      FROM JSON_TABLE(p_names,'$[*]' COLUMNS(name VARCHAR2(100) PATH '$' ERROR ON ERROR));
    IF v_count<1 OR v_count>32 OR v_count!=v_unique
    THEN RAISE_APPLICATION_ERROR(-20002,'Invalid Gods Eye View documents'); END IF;
    FOR item IN (SELECT name FROM JSON_TABLE(p_names,'$[*]' COLUMNS(name VARCHAR2(100) PATH '$' ERROR ON ERROR)))
    LOOP valid_name(item.name); END LOOP;
    SELECT COALESCE(JSON_OBJECTAGG(KEY d.name VALUE d.payload FORMAT JSON RETURNING CLOB),TO_CLOB('{}')) INTO v_result
      FROM ADMIN.PRISMA_CONTROL_DOCS d JOIN
        JSON_TABLE(p_names,'$[*]' COLUMNS(name VARCHAR2(100) PATH '$' ERROR ON ERROR)) n ON d.name=n.name;
    RETURN v_result;
  END;
  PROCEDURE WRITE_DOC(p_name VARCHAR2, p_document CLOB, p_expected NUMBER) IS v_revision NUMBER;
  BEGIN
    valid_name(p_name);
    v_revision := JSON_VALUE(p_document, '$.revision' RETURNING NUMBER NULL ON ERROR);
    IF p_document IS NULL OR p_expected IS NULL OR p_expected < 0 OR p_expected != TRUNC(p_expected)
       OR v_revision IS NULL OR v_revision != p_expected + 1
    THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid Gods Eye View revision'); END IF;
    UPDATE ADMIN.PRISMA_CONTROL_DOCS SET payload = p_document
      WHERE name = p_name AND JSON_VALUE(payload, '$.revision' RETURNING NUMBER) = p_expected;
    IF SQL%ROWCOUNT = 0 THEN
      IF p_expected != 0 THEN RAISE_APPLICATION_ERROR(-20001, 'Gods Eye View revision conflict'); END IF;
      BEGIN
        INSERT INTO ADMIN.PRISMA_CONTROL_DOCS(name,payload) VALUES(p_name,p_document);
      EXCEPTION WHEN DUP_VAL_ON_INDEX THEN RAISE_APPLICATION_ERROR(-20001, 'Gods Eye View revision conflict'); END;
    END IF;
  END;
  PROCEDURE UPSERT_POSTS(p_document CLOB, p_status VARCHAR2) IS
  BEGIN
    IF p_status IS NULL OR p_status NOT IN ('captured','ingested','processed') OR p_document IS NULL
    THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid post projection'); END IF;
    MERGE INTO ADMIN.PRISMA_SOCIAL_POSTS target USING (
      SELECT j.* FROM JSON_TABLE(p_document, '$[*]' COLUMNS (
        post_key VARCHAR2(200) PATH '$.id' ERROR ON ERROR,
        platform VARCHAR2(50) PATH '$.platform' ERROR ON ERROR,
        published_at VARCHAR2(50) PATH '$.created_at' ERROR ON ERROR,
        listing_published_at VARCHAR2(40) PATH '$.listing_published_at' NULL ON ERROR,
        listing_ready VARCHAR2(5) EXISTS PATH '$.listing_published_at',
        captured_at VARCHAR2(50) PATH '$.captured_at' NULL ON ERROR,
        payload CLOB FORMAT JSON PATH '$' ERROR ON ERROR)) j
    ) source ON (target.post_key=source.post_key)
    WHEN MATCHED THEN UPDATE SET target.payload=source.payload, target.analysis_status=p_status,
      target.listing_published_at=CASE WHEN source.listing_ready='true' THEN source.listing_published_at ELSE '?' END,
      target.listing_revision=ADMIN.PRISMA_POST_LIST_REVISION.NEXTVAL,
      target.captured_at=COALESCE(target.captured_at,
        CASE WHEN target.analysis_status='captured' THEN JSON_VALUE(target.payload,'$.ingested_at') END,source.captured_at)
      WHERE CASE p_status WHEN 'processed' THEN 3 WHEN 'ingested' THEN 2 ELSE 1 END >
            CASE target.analysis_status WHEN 'processed' THEN 3 WHEN 'ingested' THEN 2 ELSE 1 END
    WHEN NOT MATCHED THEN INSERT(post_key,platform,published_at,analysis_status,payload,captured_at,listing_published_at,listing_revision)
      VALUES(source.post_key,source.platform,source.published_at,p_status,source.payload,source.captured_at,
        CASE WHEN source.listing_ready='true' THEN source.listing_published_at ELSE '?' END,ADMIN.PRISMA_POST_LIST_REVISION.NEXTVAL);
    -- A VM capture may arrive after ingestion; fill its timestamp without replacing enriched content or status.
    MERGE INTO ADMIN.PRISMA_SOCIAL_POSTS target USING (
      SELECT j.* FROM JSON_TABLE(p_document, '$[*]' COLUMNS (
        post_key VARCHAR2(200) PATH '$.id' ERROR ON ERROR,
        captured_at VARCHAR2(50) PATH '$.captured_at' NULL ON ERROR)) j
    ) source ON (target.post_key=source.post_key)
    WHEN MATCHED THEN UPDATE SET target.captured_at=COALESCE(
      CASE WHEN target.analysis_status='captured' THEN JSON_VALUE(target.payload,'$.ingested_at') END,source.captured_at)
      WHERE target.captured_at IS NULL AND source.captured_at IS NOT NULL;
  END;
  FUNCTION LIST_POSTS(p_platform VARCHAR2, p_limit NUMBER, p_before NUMBER, p_max NUMBER) RETURN CLOB
  IS v_max NUMBER; v_total NUMBER; v_items CLOB; v_result CLOB; v_fetch NUMBER;
  BEGIN
    IF (p_platform IS NOT NULL AND p_platform NOT IN ('x','facebook','instagram','tiktok'))
       OR p_limit IS NULL OR p_limit<1 OR p_limit>100
       OR p_limit!=TRUNC(p_limit) OR (p_before IS NOT NULL AND (p_before<1 OR p_before!=TRUNC(p_before)))
       OR (p_max IS NOT NULL AND (p_max<0 OR p_max!=TRUNC(p_max)))
    THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid post pagination'); END IF;
    v_fetch := p_limit + 1;
    SELECT COALESCE(p_max,MAX(capture_seq),0) INTO v_max FROM ADMIN.PRISMA_SOCIAL_POSTS
      WHERE platform IN ('x','facebook','instagram','tiktok') AND (p_platform IS NULL OR platform=p_platform);
    SELECT COUNT(*) INTO v_total FROM ADMIN.PRISMA_SOCIAL_POSTS
      WHERE platform IN ('x','facebook','instagram','tiktok') AND (p_platform IS NULL OR platform=p_platform) AND capture_seq<=v_max;
    SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('payload' VALUE payload FORMAT JSON,
      'capture_seq' VALUE capture_seq,'analysis_status' VALUE analysis_status,
      'captured_at' VALUE COALESCE(captured_at,CASE WHEN analysis_status='captured' THEN JSON_VALUE(payload,'$.ingested_at') END) RETURNING CLOB)
      ORDER BY capture_seq DESC RETURNING CLOB),TO_CLOB('[]')) INTO v_items FROM (
        SELECT payload,capture_seq,analysis_status,captured_at FROM ADMIN.PRISMA_SOCIAL_POSTS
        WHERE platform IN ('x','facebook','instagram','tiktok') AND (p_platform IS NULL OR platform=p_platform)
        AND capture_seq<=v_max AND (p_before IS NULL OR capture_seq<p_before)
        ORDER BY capture_seq DESC FETCH FIRST v_fetch ROWS ONLY);
    SELECT JSON_OBJECT('items' VALUE v_items FORMAT JSON,'max_seq' VALUE v_max,
      'total' VALUE v_total RETURNING CLOB) INTO v_result FROM DUAL;
    RETURN v_result;
  END;
  FUNCTION LIST_ORDERED_POSTS(p_platform VARCHAR2, p_limit NUMBER, p_before VARCHAR2, p_id VARCHAR2,
    p_max NUMBER, p_sort VARCHAR2, p_order VARCHAR2) RETURN CLOB
  IS v_max NUMBER; v_result CLOB; v_fetch NUMBER;
  BEGIN
    IF (p_platform IS NOT NULL AND p_platform NOT IN ('x','facebook','instagram','tiktok'))
       OR p_limit IS NULL OR p_limit<1 OR p_limit>100 OR p_limit!=TRUNC(p_limit)
       OR (p_max IS NOT NULL AND (p_max<0 OR p_max!=TRUNC(p_max)))
       OR p_sort IS NULL OR p_sort NOT IN ('captured_at','published_at')
       OR p_order IS NULL OR p_order NOT IN ('asc','desc')
       OR (p_before IS NULL AND p_id IS NOT NULL) OR (p_before IS NOT NULL AND p_id IS NULL)
    THEN RAISE_APPLICATION_ERROR(-20002,'Invalid ordered post pagination'); END IF;
    v_fetch := p_limit + 1;
    SELECT COALESCE(p_max,MAX(capture_seq),0) INTO v_max FROM ADMIN.PRISMA_SOCIAL_POSTS
      WHERE platform IN ('x','facebook','instagram','tiktok') AND (p_platform IS NULL OR platform=p_platform);
    WITH candidates AS (
      SELECT p.*,CASE WHEN p_sort='captured_at' THEN LPAD(TO_CHAR(capture_seq,'FM99999999999999999999'),20,'0')
        ELSE COALESCE(listing_published_at,CASE WHEN p_order='asc' THEN '~' ELSE '!' END) END sort_key
      FROM ADMIN.PRISMA_SOCIAL_POSTS p WHERE platform IN ('x','facebook','instagram','tiktok')
        AND (p_platform IS NULL OR platform=p_platform) AND capture_seq<=v_max
    )
    SELECT JSON_OBJECT('max_seq' VALUE v_max,'total' VALUE (SELECT COUNT(*) FROM candidates),
      'listing_revision' VALUE (SELECT COALESCE(SUM(listing_revision),0) FROM candidates),
      'projection_pending' VALUE (SELECT COUNT(*) FROM candidates WHERE listing_revision=0 OR listing_published_at='?'),
      'items' VALUE (SELECT COALESCE(JSON_ARRAYAGG(JSON_OBJECT('payload' VALUE payload FORMAT JSON,
      'capture_seq' VALUE capture_seq,'analysis_status' VALUE analysis_status,
      'captured_at' VALUE COALESCE(captured_at,CASE WHEN analysis_status='captured' THEN JSON_VALUE(payload,'$.ingested_at') END)
      RETURNING CLOB) ORDER BY ordinal RETURNING CLOB),TO_CLOB('[]')) FROM (
      SELECT page_rows.*,ROW_NUMBER() OVER (ORDER BY
        CASE WHEN p_order='asc' THEN sort_key END ASC,CASE WHEN p_order='desc' THEN sort_key END DESC,
        CASE WHEN p_order='asc' THEN NLSSORT(post_key,'NLS_SORT=BINARY') END ASC,
        CASE WHEN p_order='desc' THEN NLSSORT(post_key,'NLS_SORT=BINARY') END DESC) ordinal FROM (
        SELECT candidates.* FROM candidates WHERE p_before IS NULL
          OR (p_order='asc' AND (sort_key>p_before OR (sort_key=p_before AND NLSSORT(post_key,'NLS_SORT=BINARY')>NLSSORT(p_id,'NLS_SORT=BINARY'))))
          OR (p_order='desc' AND (sort_key<p_before OR (sort_key=p_before AND NLSSORT(post_key,'NLS_SORT=BINARY')<NLSSORT(p_id,'NLS_SORT=BINARY'))))
        ORDER BY CASE WHEN p_order='asc' THEN sort_key END ASC,CASE WHEN p_order='desc' THEN sort_key END DESC,
          CASE WHEN p_order='asc' THEN NLSSORT(post_key,'NLS_SORT=BINARY') END ASC,
          CASE WHEN p_order='desc' THEN NLSSORT(post_key,'NLS_SORT=BINARY') END DESC FETCH FIRST v_fetch ROWS ONLY
      ) page_rows)) FORMAT JSON RETURNING CLOB) INTO v_result FROM DUAL;
    RETURN v_result;
  END;
  PROCEDURE PUBLISH(p_version VARCHAR2, p_document CLOB) IS v_old CLOB; v_version VARCHAR2(100);
  BEGIN
    v_version := JSON_VALUE(p_document,'$.version' RETURNING VARCHAR2(100) NULL ON ERROR);
    IF p_version IS NULL OR p_document IS NULL OR LENGTH(p_version) > 100
       OR NOT REGEXP_LIKE(p_version, '^[A-Za-z0-9_-]+$') OR v_version IS NULL OR p_version != v_version
    THEN RAISE_APPLICATION_ERROR(-20002, 'Invalid publication'); END IF;
    BEGIN
      INSERT INTO ADMIN.PRISMA_PUBLICATIONS(version,payload) VALUES(p_version,p_document);
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
      SELECT payload INTO v_old FROM ADMIN.PRISMA_PUBLICATIONS WHERE version=p_version;
      IF DBMS_LOB.COMPARE(v_old,p_document) != 0
      THEN RAISE_APPLICATION_ERROR(-20003, 'Immutable publication conflict'); END IF;
    END;
  END;
END PRISMA_CONTROL;"""

VIEWS = (
    "CREATE OR REPLACE VIEW ADMIN.PRISMA_V_SNAPSHOTS AS SELECT version,payload,published_at FROM ADMIN.PRISMA_PUBLICATIONS",
    """CREATE OR REPLACE VIEW ADMIN.PRISMA_V_INCIDENTS AS
       SELECT p.version,j.* FROM ADMIN.PRISMA_PUBLICATIONS p,
       JSON_TABLE(p.payload, '$.incidents[*]' COLUMNS (
         incident_id VARCHAR2(200) PATH '$.id', locality VARCHAR2(100) PATH '$.locality',
         category VARCHAR2(100) PATH '$.category', severity VARCHAR2(20) PATH '$.severity',
         source_mode VARCHAR2(20) PATH '$.mode', incident_json CLOB FORMAT JSON PATH '$')) j""",
    """CREATE OR REPLACE VIEW ADMIN.PRISMA_V_EVIDENCE AS
       SELECT p.version,j.* FROM ADMIN.PRISMA_PUBLICATIONS p,
       JSON_TABLE(p.payload, '$.evidence[*]' COLUMNS (
         evidence_id VARCHAR2(200) PATH '$.id', platform VARCHAR2(50) PATH '$.platform',
         source_mode VARCHAR2(20) PATH '$.mode', evidence_json CLOB FORMAT JSON PATH '$')) j""",
    """CREATE OR REPLACE VIEW ADMIN.PRISMA_V_SOCIAL_POSTS AS
       SELECT capture_seq,post_key,platform,published_at,analysis_status,payload,captured_at FROM ADMIN.PRISMA_SOCIAL_POSTS""",
    """CREATE OR REPLACE VIEW ADMIN.PRISMA_V_SENSOR_EVENTS AS
       SELECT p.version,j.* FROM ADMIN.PRISMA_PUBLICATIONS p,
       JSON_TABLE(p.payload, '$.sensors[*]' COLUMNS (
         sensor_event_id VARCHAR2(100) PATH '$.id', sensor_id VARCHAR2(100) PATH '$.sensor_id',
         sensor_type VARCHAR2(30) PATH '$.sensor_type', observed_at VARCHAR2(40) PATH '$.observed_at',
         lat NUMBER PATH '$.lat', lon NUMBER PATH '$.lon', locality VARCHAR2(100) PATH '$.locality',
         municipality VARCHAR2(100) PATH '$.municipality', department VARCHAR2(100) PATH '$.department',
         country VARCHAR2(100) PATH '$.country', metric VARCHAR2(30) PATH '$.metric',
         value NUMBER PATH '$.value', unit VARCHAR2(20) PATH '$.unit', status VARCHAR2(20) PATH '$.status',
         source_mode VARCHAR2(20) PATH '$.mode', is_simulated VARCHAR2(5) PATH '$.is_simulated',
         sensor_json CLOB FORMAT JSON PATH '$')) j""",
)


def install_schema(connection):
    cursor = connection.cursor()
    for statement in TABLES:
        try:
            cursor.execute(statement)
        except Exception as exc:
            if getattr(exc.args[0], "code", None) != (1430 if statement.startswith("ALTER TABLE") else 955):
                raise
    for statement in (PACKAGE_SPEC, PACKAGE_BODY, *VIEWS):
        cursor.execute(statement)
    cursor.execute("SELECT COUNT(*) FROM ALL_ERRORS WHERE OWNER='ADMIN' AND NAME='PRISMA_CONTROL'")
    if cursor.fetchone()[0]:
        raise RuntimeError("Gods Eye View database package compilation failed")
    # Existing rows are normalized once during installation, never by a listing GET.
    cursor.execute("SELECT post_key,payload FROM ADMIN.PRISMA_SOCIAL_POSTS WHERE listing_revision=0 OR listing_published_at='?'")
    for key, payload in cursor.fetchall():
        document = json.loads(payload.read() if hasattr(payload, "read") else payload)
        connection.cursor().execute("UPDATE ADMIN.PRISMA_SOCIAL_POSTS SET listing_published_at=:published, "
            "listing_revision=ADMIN.PRISMA_POST_LIST_REVISION.NEXTVAL WHERE post_key=:key AND (listing_revision=0 OR listing_published_at='?')",
            published=published_time(document.get("created_at")), key=key)
    cursor.execute("GRANT EXECUTE ON ADMIN.PRISMA_CONTROL TO AIDP_LAB_OPERATOR")
    connection.commit()


def read_document(connection, name: str) -> dict:
    _valid_name(name)
    if isinstance(connection, ObjectControlStore):
        return control_store.read_document(connection, name)
    import oracledb
    result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.READ_DOC", oracledb.DB_TYPE_CLOB, [name])
    if result is None:
        return {"revision": 0}
    document = json.loads(result.read() if hasattr(result, "read") else result)
    if not isinstance(document, dict) or type(document.get("revision")) is not int or document["revision"] < 0:
        raise ValueError("Invalid Gods Eye View document revision")
    return document


def read_documents(connection, names) -> dict:
    names = tuple(names)
    if not names or len(names) > 32 or len(set(names)) != len(names):
        raise ValueError("Invalid Gods Eye View document batch")
    for name in names:
        _valid_name(name)
    if isinstance(connection, ObjectControlStore):
        return control_store.read_documents(connection, names)
    import oracledb
    try:
        result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.READ_DOCS", oracledb.DB_TYPE_CLOB, [json.dumps(names)])
    except oracledb.DatabaseError as exc:
        message = str(exc)
        if "PLS-00302" not in message or "READ_DOCS" not in message:
            raise
        return {name: read_document(connection, name) for name in names}
    documents = json.loads(result.read() if hasattr(result, "read") else result)
    if (not isinstance(documents, dict) or set(documents) - set(names)
            or any(not isinstance(doc, dict) or type(doc.get("revision")) is not int or doc["revision"] < 0
                   for doc in documents.values())):
        raise ValueError("Invalid Gods Eye View document batch response")
    return {name: documents.get(name, {"revision": 0}) for name in names}
def write_document(connection, name: str, data: dict, expected: int) -> dict:
    _valid_name(name)
    if not isinstance(data, dict) or type(expected) is not int or expected < 0:
        raise ValueError("Invalid Gods Eye View document revision")
    document = {**data, "revision": expected + 1}
    if isinstance(connection, ObjectControlStore):
        return control_store.write_document(connection, name, data, expected)
    serialized = json.dumps(document, ensure_ascii=False, allow_nan=False)
    connection.cursor().callproc("ADMIN.PRISMA_CONTROL.WRITE_DOC", [name, serialized, expected])
    return document


def mutate_document(connection, name: str, change) -> dict:
    if isinstance(connection, ObjectControlStore):
        return control_store.mutate_document(connection, name, change)
    current = read_document(connection, name)
    updated = change(dict(current))
    result = write_document(connection, name, updated, int(current.get("revision", 0)))
    connection.commit()
    return result


def publish(connection, snapshot: dict):
    if isinstance(connection, ObjectControlStore):
        return control_store.publish(connection, snapshot)
    if (not isinstance(snapshot, dict) or not isinstance(snapshot.get("version"), str)
            or not re.fullmatch(r"[A-Za-z0-9_-]{1,100}", snapshot["version"])
            or not isinstance(snapshot.get("incidents"), list) or not isinstance(snapshot.get("evidence"), list)):
        raise ValueError("Invalid Gods Eye View publication")
    serialized = json.dumps(snapshot, ensure_ascii=False, sort_keys=True, allow_nan=False)
    connection.cursor().callproc("ADMIN.PRISMA_CONTROL.PUBLISH",
        [snapshot["version"], serialized])
    connection.commit()


def purge_synthetic_posts(connection, operation_id):
    if isinstance(connection, ObjectControlStore):
        return control_store.purge_synthetic_posts(connection, operation_id)
    result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.PURGE_SYNTHETIC_POSTS", int, [operation_id])
    connection.commit()
    return result


def reset_version(connection):
    if isinstance(connection, ObjectControlStore):
        return control_store.reset_version(connection)
    return connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.RESET_VERSION", int, [])


def sensor_reset_version(connection):
    if isinstance(connection, ObjectControlStore):
        return control_store.sensor_reset_version(connection)
    return connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.SENSOR_RESET_VERSION", int, [])


def publications(connection):
    if isinstance(connection, ObjectControlStore):
        yield from control_store.publications(connection)
        return
    import oracledb
    after = None
    while True:
        result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.LIST_PUBLICATIONS", oracledb.DB_TYPE_CLOB, [after])
        page = json.loads(result.read() if hasattr(result, "read") else result)
        if not page:
            return
        snapshot = page[0]
        if after is not None and snapshot["version"] <= after:
            raise ValueError("Publication history did not advance")
        after = snapshot["version"]
        yield snapshot


def replace_synthetic_publication(connection, operation_id, old, new):
    if isinstance(connection, ObjectControlStore):
        return control_store.replace_synthetic_publication(connection, operation_id, old, new)
    connection.cursor().callproc("ADMIN.PRISMA_CONTROL.REPLACE_SYNTHETIC_PUBLICATION", [operation_id, old, new])
    connection.commit()


def replace_sensor_publication(connection, operation_id, sensor_type, old, new):
    from .sensors import SENSOR_TYPES
    if not isinstance(sensor_type, str) or sensor_type not in (*SENSOR_TYPES, "all"):
        raise ValueError("Invalid sensor reset type")
    if isinstance(connection, ObjectControlStore):
        return control_store.replace_sensor_publication(connection, operation_id, sensor_type, old, new)
    connection.cursor().callproc("ADMIN.PRISMA_CONTROL.REPLACE_SENSOR_PUBLICATION", [operation_id, sensor_type, old, new])
    connection.commit()


def upsert_posts(connection, records, analysis_status, ingested_at=None, batch_key=None):
    """Project durable capture/ingestion/analysis progress without replacing a later state."""
    if isinstance(connection, ObjectControlStore):
        return control_store.upsert_posts(connection, records, analysis_status, ingested_at, batch_key)
    if analysis_status not in {"captured", "ingested", "processed"}:
        raise ValueError("Invalid post analysis status")
    documents = {}
    for record in records:
        if record.get("mode") == "simulation":
            record = {**record, "mode": canonical_mode(record["mode"])}
        key = f"{record['platform']}:{record['source_id']}"
        if (len(key) > 200 or not record["source_id"] or not isinstance(record.get("created_at"), str)
                or not re.fullmatch(r"[a-z][a-z0-9_]{0,49}", record["platform"])):
            raise ValueError("Invalid post projection identity")
        document = {**record, "id": key}
        document["listing_published_at"] = published_time(record.get("created_at"))
        captured_at = record.get("captured_at") or (ingested_at if analysis_status == "captured" else None)
        if captured_at is None and record.get("mode") == "real":
            captured_at = record.get("observed_at")
        document.update({name: value for name, value in (("captured_at", captured_at), ("ingested_at", ingested_at), ("batch_key", batch_key))
                         if value is not None})
        documents[key] = document
    if not documents:
        return
    payload = json.dumps(list(documents.values()), ensure_ascii=False, allow_nan=False)
    cursor = connection.cursor()
    try:
        cursor.callproc("ADMIN.PRISMA_CONTROL.UPSERT_POSTS", [payload, analysis_status])
    except Exception as exc:
        # Concurrent VM/stream inserts may race once; the second MERGE observes the winner.
        if not exc.args or getattr(exc.args[0], "code", None) != 1:
            raise
        cursor.callproc("ADMIN.PRISMA_CONTROL.UPSERT_POSTS", [payload, analysis_status])
    connection.commit()


def query_posts(connection, platform, limit, before_seq=None, max_seq=None):
    """Stable insertion-order page; the first page fixes the capture sequence ceiling."""
    if isinstance(connection, ObjectControlStore):
        return control_store.query_posts(connection, platform, limit, before_seq, max_seq)
    import oracledb
    if (platform is not None and platform not in ("x", "facebook", "instagram", "tiktok")
            or type(limit) is not int or not 1 <= limit <= 100
            or any(value is not None and (type(value) is not int or value < minimum)
                   for value, minimum in ((before_seq, 1), (max_seq, 0)))):
        raise ValueError("Invalid post pagination")
    result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.LIST_POSTS", oracledb.DB_TYPE_CLOB,
                                          [platform, limit, before_seq, max_seq])
    document = json.loads(result.read() if hasattr(result, "read") else result)
    items = [{**item["payload"], "capture_seq": item["capture_seq"], "analysis_status": item["analysis_status"],
              "captured_at": item.get("captured_at") or item["payload"].get("captured_at")}
             for item in document["items"][:limit]]
    return {**document, "items": items, "next_seq": items[-1]["capture_seq"] if len(document["items"]) > limit else None}


def query_ordered_posts(connection, platform, limit, position=None, maximum=None, sort="published_at", order="desc"):
    if isinstance(connection, ObjectControlStore):
        return control_store.query_ordered_posts(connection, platform, limit, position, maximum, sort, order)
    import oracledb
    if (platform is not None and platform not in ("x", "facebook", "instagram", "tiktok")
            or type(limit) is not int or not 1 <= limit <= 100 or sort not in {"published_at", "captured_at"}
            or order not in {"asc", "desc"} or maximum is not None and (type(maximum) is not int or maximum < 0)):
        raise ValueError("Invalid ordered post pagination")
    before, identity = position["key"] if position else (None, None)
    if before is not None:
        before = str(before).zfill(20) if sort == "captured_at" else before if before not in {"", "\uffff"} else "~" if order == "asc" else "!"
    try:
        result = connection.cursor().callfunc("ADMIN.PRISMA_CONTROL.LIST_ORDERED_POSTS", oracledb.DB_TYPE_CLOB,
                                              [platform, limit, before, identity, maximum, sort, order])
    except Exception as exc:
        error = exc.args[0] if exc.args else None
        # Rolling upgrades retain the original reader until the package is installed.
        if (getattr(error, "code", None) == 6550 and "PLS-00302" in str(error)
                and "LIST_ORDERED_POSTS" in str(error)):
            return None
        raise
    document = json.loads(result.read() if hasattr(result, "read") else result)
    # An older producer may still write during rollout; never sort its unnormalized dates.
    if document.get("projection_pending", 0):
        return None
    return {**document, "items": [{**row["payload"], "capture_seq": row["capture_seq"], "analysis_status": row["analysis_status"],
                                  "captured_at": row.get("captured_at") or row["payload"].get("captured_at")}
                                 for row in document["items"]]}
